//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Toy.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Customer
    {
        public int IdCustomer { get; set; }
        public string Name { get; set; }
        public string PhoneNumber { get; set; }
        public Nullable<int> IdPeronalDiscount { get; set; }
        public Nullable<int> Toy { get; set; }
    }
}
